- name: Install
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: ~/.rustup
    warn: false

- name: Copy config
  file:
    src: "{{ role_path }}/files/config.toml"
    dest: ~/.cargo/config.toml
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    force: true
  tags:
    - config

- name: Set toolchain
  shell: ~/.cargo/bin/rustup default stable
  args:
    creates: ~/.rustup/toolchains/stable*

- name: Generate shell completions
  shell: ~/.cargo/bin/rustup completions zsh
  register: rust_completions

- name: Save completions
  copy:
    content: "{{ rust_completions.stdout }}"
    dest: ~/.zfunc/_rustup

- name: Run OS specific tasks
  include_tasks: '{{ item }}'
  vars:
    params:
      files:
        - "{{ role_path }}/tasks/{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ role_path }}/tasks/{{ ansible_facts['os_family'] | lower }}.yml"
  loop: "{{ query('first_found', params, errors='ignore') }}"

- name: Install packages
  shell: ~/.cargo/bin/cargo install {{ item.package }}
  args:
    creates: "~/.cargo/bin/{{ item.bin }}"
  when: install_rust_packages is true
  with_items:
    - package: cargo-edit
      bin: carg-add
    - package: cargo-tarpaulin
      bin: cargo-tarpaulin
