libvirt_image_file: "{{ lookup('env', 'HOME') }}/.local/share/libvirt/images/windows.iso"
libvirt_storage_file: "{{ lookup('env', 'HOME') }}/.local/share/libvirt/images/windows.qcow2"
shared_dir: "{{ lookup('env', 'HOME') }}/line6"
vm_name: windows
vm_ram_mb: 8192
vm_storage_gb: 50G
vm_vcpus: 8
