- name: Run OS specific tasks
  include_tasks: "{{ item }}"
  vars:
    params:
      files:
        - "{{ role_path }}/tasks/{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ role_path }}/tasks/{{ ansible_facts['os_family'] | lower }}.yml"
  loop: "{{ query('first_found', params, errors='ignore') }}"

- name: Install
  package:
    name: fish
    state: latest
  become: "{{ should_sudo_install }}"

- name: Copy config
  file:
    src: "{{ role_path }}/files"
    dest: ~/.config/fish
    state: link
    force: true
  tags:
    - config

- name: Download fisher
  get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    dest: /tmp/fisher.fish
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0755'

- name: Install fisher
  shell:
    cmd: source /tmp/fisher.fish && fisher install jorgebucaran/fisher
    executable: fish

