- name: Run OS specific tasks
  import_tasks: "{{ playbook_dir }}/tasks/run_os_specific_tasks.yml"

- name: Install
  package:
    name: fish
    state: latest
  become: "{{ should_sudo_install }}"

- name: Copy config
  file:
    src: "{{ role_path }}/files"
    dest: ~/.config/fish
    state: link
    force: true
  tags:
    - config

- name: Download fisher
  get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    dest: /tmp/fisher.fish
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0755'

- name: Install fisher
  shell:
    cmd: source /tmp/fisher.fish && fisher install jorgebucaran/fisher
    executable: fish
    creates: ~/.config/fisher/functions/fisher.fish

- name: Install packages
  shell:
    cmd: fisher update
    executable: fish
