#!/usr/bin/env python

from os import path, mkdir

role_name = input('Role name: ')

role_path = path.join(path.dirname(__file__), 'roles', role_name)

if path.exists(role_path) == True:
    print(f'{role_path} already exists')
    exit(1)

mkdir(role_path)

directories = {
    'tasks': ['main.yml'],
    'files': []
}

for directory in directories:
    directory_path = path.join(role_path, directory)
    mkdir(directory_path)

    for file in directories[directory]:
        file_path = path.join(directory_path, file)
        open(file_path, 'w+').close()
