#!/usr/bin/env python

from os import path, mkdir
import argparse

parser = argparse.ArgumentParser(description='Add a new role')
parser.add_argument('role', nargs='?', help='Name for the new role')
args = parser.parse_args()

role_name = args.role or input('Role name: ').lower()

role_path = path.join(path.dirname(__file__), 'roles', role_name)

if path.exists(role_path) == True:
    print(f'{role_path} already exists!')
    exit(1)

mkdir(role_path)

directories = {
    'tasks': ['main.yml'],
    'files': []
}

for directory in directories:
    directory_path = path.join(role_path, directory)
    mkdir(directory_path)

    for file in directories[directory]:
        file_path = path.join(directory_path, file)
        open(file_path, 'w+').close()
