- hosts: 
    - all
    - localhost
  connection: local
  roles:
    - common
    - alacritty
    - role: awesome
      when: ansible_facts['system'] | lower == 'linux'
    - aws
    - role: bspwm
      when: ansible_facts['system'] | lower == 'linux'
    - chrome
    - docker
    - git
    - role: gnome
      when: ansible_facts['system'] | lower == 'linux'
    - haskell
    - role: i3
      when: ansible_facts['system'] | lower == 'linux'
    - kitty
    - lazygit
    - node
    - role: polybar
      when: ansible_facts['system'] | lower == 'linux'
    - rust
    - ssh
    - tealdeer
    - tmux
    - vim
    - vscode
    - zsh
