- hosts: 
    - all
    - localhost
  connection: local
  vars:
    is_linux: "{{ (ansible_facts['os_family'] | lower == 'linux') }}"
    is_mac: "{{ (ansible_facts['os_family'] | lower == 'darwin') }}"
    should_sudo_install: "{{ not is_mac }}"
    should_use_cargo: false
  roles:
    - role: homebrew
      when: is_mac
    - common
    - alacritty
    - role: awesome
      when: is_linux
    - aws
    - bat
    - bottom
    - role: bspwm
      when: is_linux
    # - chrome
    - role: docker
      when: is_linux
    - exa
    - role: flatpak
      when: is_linux
    - git
    - role: gnome
      when: is_linux
    # - haskell
    - role: i3
      when: is_linux
    - kitty
    - lazygit
    - node
    - nomad
    - role: polybar
      when: is_linux
    - procs
    - ripgrep
    - rust
    - ssh
    - tealdeer
    - tmux
    - vim
    - vscode
    - zsh
