#!/usr/bin/env bash

function apt_install() {

  local -r apt_pkgs=(
    bspwm
    sxhkd
    tmux
    vim
    vscode
  )

  sudo apt install -y "${apt_pkgs[@]}"
}

function cargo_install() {

  local -r cargo_pkgs=(
    bat
    exa
    ripgrep
  )

  cargo install "${cargo_pkgs[@]}"
}

function npm_install() {

  local -t npm_pkgs=()

  npm install -g "${npm_pkgs[@]}"
}

function pacman_install() {
  
  local -r pacman_pkgs=(
    bspwm
    sxhkd
    tmux
    vim
    vscode
  )

  sudo pacman -Syu --noconfirm "${pacman_pkgs[@]}"
}

function pip_install() {

  local -r pip_pkgs=(
    awscli
    cfn-lint
  )

  pip install --user --upgrade "${pip_pkgs[@]}"
}

function main() {

  # Install packages using the OS package manager
  if command -v apt > /dev/null 2>&1; then
    apt_install
  else
    pacman_install
  fi

  # Install packages using language specific package managers
  cargo_install
  npm_install
  pip_install
}

main