- name: Install
  dnf:
    name:
      - gnome-shell-extension-user-theme
      - gnome-shell-theme-yaru
    state: latest
  become: true
  when: ansible_facts['os_family'] | lower == 'redhat'

- name: Configure
  community.general.dconf:
    key: "/org/gnome/shell/extensions/user-theme/{{ setting.key }}"
    value: "{{ setting.value }}"
  with_items:
    - key: name
      value: "'Yaru-dark'"
  loop_control:
    loop_var: setting
