- name: Enable COPR
  community.general.copr:
    name: atim/lazygit
  become: true
  when: ansible_facts['os_family'] | lower == 'redhat'

- name: Enable PPA
  apt_repository:
      repo: lazygit-team/release
  become: true
  when: ansible_facts['os_family'] | lower == 'debian'

- name: Install
  package:
    name: lazygit
    state: latest
  become: true
