- name: Run OS specific tasks
  include_tasks: "{{ item }}"
  with_fileglob:
    - "{{ role_path }}/tasks/{{ ansible_facts['system'] | lower }}.yml"
    - "{{ role_path }}/tasks/{{ ansible_facts['os_family'] | lower }}.yml"
    - "{{ role_path }}/tasks/{{ ansible_facts['distribution'] | lower }}.yml"
  # vars:
  #   params:
  #     files:
  #       - "{{ role_path }}/tasks/{{ ansible_facts['system'] | lower }}.yml"
  #       - "{{ role_path }}/tasks/{{ ansible_facts['os_family'] | lower }}.yml"
  #       - "{{ role_path }}/tasks/{{ ansible_facts['distribution'] | lower }}.yml"
  # loop: "{{ query('first_found', params, errors='ignore') }}"
