- name: Run OS specific tasks
  include_tasks: "{{ item }}"
  with_fileglob:
    - "{{ role_path }}/tasks/{{ ansible_facts['distribution'] | lower }}.yml" # e.g. Fedora, Ubuntu
    - "{{ role_path }}/tasks/{{ ansible_facts['os_family'] | lower }}.yml"    # e.g. RedHat, Darwin
    - "{{ role_path }}/tasks/{{ ansible_facts['system'] | lower }}.yml"       # e.g. Linux, MacOS
