- name: Install
  dnf:
    name: 
      - vagrant
      - vagrant-libvirt
    disablerepo: hashicorp
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: true

- name: Enable virtnetworkd
  systemd:
    name: virtnetworkd
    state: started
  become: true
