- name: Run OS specific tasks
  import_tasks: "{{ playbook_dir }}/tasks/run_os_specific_tasks.yml"

- name: Install
  package:
    name: "{{ is_linux | ternary('code', 'visual-studio-code') }}"
    state: latest
  become: "{{ should_sudo_install }}"

- name: Create config directory
  file: 
    path: "{{ config_path }}/Code/User"
    state: directory
    mode: '0755'

- name: Copy config
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ config_path }}/Code/User/{{ item }}"
    state: link
    force: true
  loop:
    - keybindings.json
    - settings.json
  tags:
    - config

- name: Install extensions
  shell: "code --install-extension {{ item }}"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.vscode/extensions/{{ item }}*"
  loop: "{{ lookup('file', '{{ role_path }}/files/extensions.txt').splitlines() }}"

- name: Setup extensions cron job
  cron:
    name: backup VSCode extensions
    special_time: weekly
    job: code --list-extensions > ~/.dotfiles/roles/vscode/files/extensions.txt
