- name: Run OS specific tasks
  include_tasks: '{{ item }}'
  vars:
    params:
      files:
        - "{{ role_path }}/tasks/{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ role_path }}/tasks/{{ ansible_facts['os_family'] | lower }}.yml"
  loop: "{{ query('first_found', params, errors='ignore') }}"

- name: Install
  package:
    name: code
    state: latest
  become: true

- name: Create config directory
  file: 
    path: ~/.config/Code/User
    state: directory
    mode: '0755'

- name: Copy config
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: ~/.config/Code/User/{{ item }}
    state: link
    force: true
  loop:
    - keybindings.json
    - settings.json

- name: Install extensions
  shell: "code --install-extension {{ item }}"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.vscode/extensions/{{ item }}*"
  loop: "{{ lookup('file', '{{ role_path }}/files/extensions.txt').splitlines() }}"

- name: Setup extensions cron job
  cron:
    name: backup VSCode extensions
    special_time: weekly
    job: code --list-extensions > ~/.dotfiles/roles/vscode/files/extensions.txt
