- name: Run OS specific tasks
  include_tasks: '{{ item }}'
  vars:
    params:
      files:
        - "{{ role_path }}/tasks/{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ role_path }}/tasks/{{ ansible_facts['os_family'] | lower }}.yml"
  loop: "{{ query('first_found', params, errors='ignore') }}"

- name: Install
  package:
    name: "{{ is_linux | ternary('code', 'visual-studio-code') }}"
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: "{{ should_sudo_install }}"

- name: Create config directory
  file: 
    path: "{{ config_path }}/Code/User"
    state: "{{ should_teardown | ternary('absent', 'directory') }}"
    mode: '0755'
  tags:
    - config

- name: Copy config
  file:
    # src: "{{ role_path }}/files/{{ item }}"
    src: "{{ should_teardown | ternary(omit, role_path~'/files/'~item) }}"
    dest: "{{ config_path }}/Code/User/{{ item }}"
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    force: true
  loop:
    - keybindings.json
    - settings.json
  tags:
    - config

- name: Install extensions
  shell: "code --install-extension {{ item }}"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.vscode/extensions/{{ item }}*"
  loop: "{{ lookup('file', '{{ role_path }}/files/extensions.txt').splitlines() }}"

- name: Setup extensions cron job
  cron:
    name: backup VSCode extensions
    special_time: weekly
    job: code --list-extensions > ~/.dotfiles/roles/vscode/files/extensions.txt
