#!/usr/bin/env bash
# download util from here using brew tap fullscreen/tap or directly from https://github.com/Fullscreen/aws-rotate-key

set -eo pipefail

# check to see if aws-rotate-key exists on the system
if ! which /usr/local/bin/aws-rotate-key; then
	>&2 echo "Could not find the aws-rotate-key utility on this system"
	exit 2
fi

credentials_file="${AWS_CREDENTIALS_FILE:-${HOME}/.aws/credentials}"

profiles=$(grep "^\[" "${credentials_file}" | sort -u | xargs | tr '\[' ' ' | tr '\]' ' ')

echo "Started all IAM key rotation $(date +%Y-%m-%d_%H-%M-%S)"

for profile in $profiles; do
	echo -e "\nRotating IAM key for ${profile}"
	/usr/local/bin/aws-rotate-key --profile "${profile}" -y
done

echo "Finished all IAM key rotations $(date +%Y-%m-%d_%H-%M-%S)"
