- name: Install
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - bspwm
    - sxhkd
  become: true

- name: Copy config
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/{{ item }}"
    state: link
    force: true
  loop:
    - bspwm
    - sxhkd
  tags:
    - config
