- name: Install
  package:
    name: "{{ item }}"
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  loop:
    - bspwm
    - sxhkd
  become: true

- name: Copy config
  file:
    src: "{{ should_teardown | ternary(omit, role_path~'/files') }}"
    dest: "~/.config/{{ item }}"
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    force: true
  loop:
    - bspwm
    - sxhkd
  tags:
    - config
