#!/usr/bin/env bash

# Set some variables
export gap=20
export PANEL_HEIGHT=25

# Set workspace names
bspc monitor -d I II III IV V VI VII VIII IX X

# Set gaps
bspc config window_gap $gap
bspc config top_padding $gap
bspc config top_monocle_padding $((PANEL_HEIGHT - gap))

# Remove gaps if there is a single window
bspc config single_monocle      true
bspc config gapless_monocle     true
bspc config borderless_monocle  true

# Set 1 pixel border
bspc config border_width 1

# Set insertion scheme
bspc config automatic_scheme alternate

# Change focus with mouse pointer
bspc config focus_follows_pointer true

# Auto remove monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

##Color settings
bspc config focused_border_color "#ABB2BF"
bspc config normal_border_color "#282C34"
bspc config presel_feedback_color "#1ABB9B"

#Settings for manual splitting
bspc config split_ratio 0.5

# Keybindings daemon
sxhkd &

# Map super to super+shift+space
xcape -e 'Super_L=Super_L|Shift_L|space' &

# Status Bar
limepanel &
