- name: Copy config
  file:
    src: "{{ role_path }}/files/config"
    dest: ~/.ssh/config
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    mode: '0600'
    force: true
  tags:
    - config
