- name: Make dir
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Copy config
  file:
    src: "{{ role_path }}/files/config"
    dest: ~/.ssh/config
    state: link
    mode: '0600'
    force: true
  tags:
    - config
