- name: Install
  package:
    name: tealdeer
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: "{{ should_sudo_install }}"
  when: not should_use_cargo

- name: Install (cargo)
  shell: ~/.cargo/bin/cargo install tealdeer
  args:
    creates: ~/.cargo/bin/tldr
  with_items:
    - package: tealdeer
      bin: tldr
  when: should_use_cargo

- name: Copy config
  file:
    src: "{{ should_teardown | ternary(omit, role_path~'/files') }}"
    dest: ~/.config/tealdeer
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    force: true
  tags:
    - config
