- name: Install
  package:
    name: tealdeer
    state: present
  when: not should_use_cargo
  become: "{{ should_sudo_install }}"

- name: Install (cargo)
  shell: ~/.cargo/bin/cargo install tealdeer
  args:
    creates: ~/.cargo/bin/tldr
  with_items:
    - package: tealdeer
      bin: tldr
  when: should_use_cargo

- name: Copy config
  file:
    src: "{{ role_path }}/files"
    dest: ~/.config/tealdeer
    state: link
    force: true
  tags:
    - config
