- name: Install
  package:
    name: flatpak
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: true

- name: Add Flathub
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: true
