- name: Install
  package:
    name: zsh
    state: latest
  become: true
  when: is_linux

- name: Install Antigen
  get_url:
    url: https://git.io/antigen
    dest: ~/antigen.zsh
  when: is_linux

# Brew install Antigen for Mac
- name: Install Antigen
  package:
    name: antigen
    state: latest
  become: false
  when: is_mac

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh
  register: install_omz

- name: Copy config
  file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  with_items:
    - src: zshrc
      dest: ~/.zshrc
    - src: p10k.zsh
      dest: ~/.p10k.zsh
  tags:
    - config

- name: Set default shell
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh
  become: true
  when: is_linux
