window:
  dimensions:
   columns: 90
   lines: 30

  padding:
    x: 5
    y: 2 

  decorations: full #none

  startup_mode: Maximized

  opacity: 1.0

font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  bold:
    family: Hack Nerd Font Mono
    style: Bold

  italic:
    family: Hack Nerd Font Mono
    style: Italic

  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  size: 11.0

colors:
  primary:
    background: '0x282c34'
    foreground: '0xabb2bf'

  normal:
    black:   '0x282c34'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'

