- name: Run OS specific tasks
  import_tasks: "{{ playbook_dir }}/tasks/run_os_specific_tasks.yml"

- name: Copy config
  file:
    src: "{{ role_path }}/files"
    dest: ~/.config/zed
    state: link
    force: true
  tags:
    - config
