- name: Install CLI tools
  pip:
    name:
      - awscli
      - aws-shell
      - cfn-lint
    extra_args: "--user --upgrade"

- name: Copy key rotation script
  file:
    src: "{{ role_path }}/files/rotate-iam-keys"
    dest: "~/bin/rotate-iam-keys"
    state: link
    force: true

- name: Create log directory
  file:
    path: /var/log/aws-iam
    state: directory
    mode: '0777'  
  become: true

- name: Setup key rotation cron job
  cron:
    name: rotate IAM keys
    minute: '1'
    hour: '12'
    job: ~/bin/rotate-iam-keys &> /var/log/aws-iam/$(date +\%Y-\%m-\%d).log
