- name: Install
  package:
    name: kitty
    state: latest
  become: "{{ should_sudo_install }}"

- name: Copy config
  file:
    src: "{{ role_path }}/files"
    dest: ~/.config/kitty
    state: link
    force: true
  tags:
    - config
