- name: Install
  package:
    name: kitty
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: "{{ should_sudo_install }}"

- name: Copy config
  file:
    src: "{{ should_teardown | ternary(omit, role_path~'/files') }}"
    dest: ~/.config/kitty
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    force: true
  tags:
    - config
