- name: Install
  package:
    name: i3
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: true

- name: Copy config
  file:
    src: "{{ should_teardown | ternary(omit, role_path~'/files') }}"
    dest: "~/.config/{{ item }}"
    state: "{{ should_teardown | ternary('absent', 'link') }}"
  with_items:
    - i3
    - i3status
  tags:
    - config
