# Required dependency for community.general.dconf module
- name: Install psutil
  pip:
    name: psutil
    extra_args: "--user --upgrade"

- name: Enable Flat Remix PPA
  apt_repository:
      repo: daniruiz/flat-remix
  become: true
  when: ansible_facts['os_family'] | lower == 'debian'

- name: Enable GDM Wallpaper COPR
  community.general.copr:
    name: zirix/gdm-wallpaper
  become: true
  when: ansible_facts['os_family'] | lower == 'redhat'

- name: Install packages
  apt:
    name:
      - flat-remix
      - gnome-tweaks
    state: latest
  become: true
  when: ansible_facts['os_family'] | lower == 'debian'

- name: Install packages
  dnf:
    name:
      - flat-remix-icon-theme
      - gdm-wallpaper
      - gnome-shell-extension-appindicator
      - gnome-tweaks
    state: latest
  become: true
  when: ansible_facts['os_family'] | lower == 'redhat'

- name: Configure
  include_tasks: "extensions/{{ extension }}.yml"
  loop:
    - dash-to-dock
    - desktop
    - openweather
    - shortcuts
    - user-theme
  loop_control:
    loop_var: extension
