- name: Install
  package:
    name: git
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: "{{ should_sudo_install }}"

- name: Copy config
  file:
    src: "{{ should_teardown | ternary(omit, role_path~'/files') }}"
    dest: ~/.config/git
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    force: true
  tags:
    - config
    
- name: Install delta
  package:
    name: git-delta
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: "{{ should_sudo_install }}"
  when: not should_use_cargo

- name: Install delta (cargo)
  shell: ~/.cargo/bin/cargo install git-delta
  args:
    creates: ~/.cargo/bin/delta
  when: should_use_cargo
