- name: Install
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew

- name: Patch module
  ansible.posix.patch:
    src: "{{ role_path }}/files/homebrew.patch"
    dest: ~/.ansible/collections/ansible_collections/community/general/plugins/modules/packaging/os/homebrew.py
