- name: Add stable repository
  yum_repository:
    file: kubernetes
    name: kubernetes
    description: Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
    enabled: 1
    gpgcheck: 1
    repo_gpgcheck: 1
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
  become: true

- name: Install minikube
  dnf:
    name: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    disable_gpg_check: true
    state: latest
  become: "{{ should_sudo_install }}"

- name: Enable COPR
  community.general.copr:
    name: rubemlrm/kubectx
  become: true

