- name: Run OS specific tasks
  import_tasks: "{{ playbook_dir }}/tasks/run_os_specific_tasks.yml"

- name: Install
  package:
    name: "{{ item }}"
    state: latest
  loop: 
    - kubectl
    - kubectx
  become: "{{ should_sudo_install }}"
