- name: Run OS specific tasks
  include_tasks: '{{ item }}'
  vars:
    params:
      files:
        - "{{ role_path }}/tasks/{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ role_path }}/tasks/{{ ansible_facts['os_family'] | lower }}.yml"
  loop: "{{ query('first_found', params, errors='ignore') }}"

- name: Install
  package:
    name: bottom
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: "{{ should_sudo_install }}"
  when: not should_use_cargo

- name: Install (cargo)
  shell: ~/.cargo/bin/cargo install bottom
  args:
    creates: ~/.cargo/bin/btm
  when: should_use_cargo
