- name: Run OS specific tasks
  import_tasks: "{{ playbook_dir }}/tasks/run_os_specific_tasks.yml"

- name: Install
  package:
    name: bottom
    state: present
  become: "{{ should_sudo_install }}"
  when: not should_use_cargo

- name: Install (cargo)
  shell: ~/.cargo/bin/cargo install bottom
  args:
    creates: ~/.cargo/bin/btm
  when: should_use_cargo
