- name: Install
  package:
    name: polybar
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: true  

- name: Copy config
  file:
    src: "{{ should_teardown | ternary(omit, role_path~'/files') }}"
    dest: ~/.config/polybar
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    force: true
  tags:
    - config
