#!/usr/bin/env bash

alias l='ls -hl'
alias ll='ls -ahl'
alias lls='ll | less'

# Use `eza` as an `ls` replacement
if command -v eza > /dev/null 2>&1; then
  alias ls='eza --color=always'
fi

# Use `bat` as a `cat` replacement
if command -v bat > /dev/null 2>&1; then
  alias cat='bat'
fi

# Use `ripgrep` as a `grep` replacement
if command -v rg > /dev/null 2>&1; then
  alias grep='rg'
fi

# Use `bottom` (`btm`) as a `top` replacement
if command -v btm > /dev/null 2>&1; then
  alias top='btm -b'
fi

# Alias xclip to use `clipboard` by default
alias xclip="xclip -selection clipboard"

# Alias `python` to `python3`
if command -v python3 > /dev/null 2>&1; then
    alias python="python3"
fi

# Alias `pip` to `pip3`
if command -v pip3 > /dev/null 2>&1; then
    alias pip="pip3"
fi

# Use `neovim` as a `vim` replacement
if command -v nvim > /dev/null 2>&1; then
    alias vim="nvim"
fi

if command -v kubectl > /dev/null 2>&1; then
  alias kc="kubectl"
fi

alias ts='yo simple-ts'

alias dc='docker-compose'
