- name: Install
  package:
    name: tmux
    state: latest
  become: true
    
- name: Copy config
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: ~/.tmux.conf
    state: link
    force: true
  tags:
    - config
