- name: Install
  package:
    name: tmux
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: true
    
- name: Copy config
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: ~/.tmux.conf
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    force: true
  tags:
    - config
