- name: Download nvm
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
    dest: /tmp/nvm-install.sh
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0755'

- name: Install nvm
  shell:
    cmd: /tmp/nvm-install.sh
    creates: ~/.nvm
  environment: 
    PROFILE: /dev/null

- name: Install
  shell: source ~/.nvm/nvm.sh && nvm install {{ item }}
  loop:
    - --lts
    - 14
    - 12
    - 10

- name: Install packages
  shell: source ~/.nvm/nvm.sh && npm install -g {{ item }}
  loop:
    - aws-cdk
    - eslint
    - https://github.com/DomParfitt/generator-simple-ts #generator-simple-ts
    - typescript
    - yo
