- name: Add user to sudoers
  copy:
    content: "{{ lookup('env', 'USER') }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ lookup('env', 'USER') }}"
    validate: visudo -csf %s
  become: true
  when: is_linux

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - ~/.config
    - ~/.zfunc
    - ~/bin
    - ~/Pictures
    - ~/projects
    - ~/projects/work

- name: Copy files
  file:
    src: "{{ should_teardown | ternary(omit, role_path~'/files') }}"
    dest: "{{ item.dest }}"
    state: "{{ should_teardown | ternary('absent', 'link') }}"
  with_items:
    - src: aliases
      dest: ~/.aliases
    - src: fonts
      dest: ~/.fonts
    - src: functions
      dest: ~/.functions
    - src: Xresources
      dest: ~/.Xresources
    - src: wallpapers
      dest: ~/Pictures/wallpapers

- name: Run OS specific tasks
  include_tasks: '{{ item }}'
  vars:
    params:
      files:
        - "{{ role_path }}/tasks/{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ role_path }}/tasks/{{ ansible_facts['os_family'] | lower }}.yml"
  loop: "{{ query('first_found', params, errors='ignore') }}"

- name: Install packages
  package:
    name:
      - curl
      - feh
      - firefox
      - make
      - most
      - neofetch
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: "{{ should_sudo_install }}"
