#!/usr/bin/env bash

# Set some variables
export gap=20
export PANEL_HEIGHT=25

# Set workspace names
bspc monitor -d I II III IV V VI VII VIII IX

# Set up for multi-monitor if necessary
monitors=$(xrandr -q | grep -wc connected)

if [[ $monitors == 2 ]]; then

  # Get the name of the external monitor
  second_monitor=$(xrandr -q | grep -w connected | awk '$0 !~ /eDP-1/ {print $1}')

  # Use the external monitor as the primary
  bspc monitor "${second_monitor}" -d I II III IV V VI
  
  # Use built-in monitor as secondary
  bspc monitor eDP-1 -d VII VIII IX
fi

# Set gaps
bspc config window_gap          $gap
bspc config top_padding         $gap
#bspc config top_monocle_padding $((PANEL_HEIGHT - gap)) # Uncomment if not using xfce4-panel

# Remove gaps if there is a single window
bspc config single_monocle      true
bspc config gapless_monocle     true
bspc config borderless_monocle  true

# Set 1 pixel border
bspc config border_width 1 

# Set insertion scheme
bspc config automatic_scheme alternate

# Change focus with mouse pointer
bspc config focus_follows_pointer true

# Mouse controls
bspc config pointer_modifier    mod4
bspc config pointer_action1     move

# Auto remove monitors
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

# Color settings
bspc config focused_border_color  "#ABB2BF"
bspc config normal_border_color   "#282C34"
bspc config presel_feedback_color "#1ABB9B"

# Settings for manual splitting
bspc config split_ratio 0.5

# Autostart required programs
~/.config/bspwm/autostart.sh