- name: Add repository
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: true
  when: ansible_facts['os_family'] | lower == 'redhat'

- name: Install
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - containerd.io
    - docker-ce
    - docker-ce-cli
  become: true

- name: Add user to group
  user:
    name: "{{ lookup('env', 'USER') }}"
    group: docker
  become: true

- name: Enable daemon
  systemd:
    name: docker
    enabled: true
  become: true

- name: Setup prune cron job
  cron:
    name: prune Docker images
    special_time: daily
    job: docker image prune --force
