- name: Install
  package:
    name: starship
    state: latest
  become: "{{ should_sudo_install }}"

- name: Copy config
  file:
    src: "{{ role_path }}/files/starship.toml"
    dest: ~/.config/starship.toml
    state: link
    force: true
  tags:
    - config
