- name: Install
  package:
    name:
      # - vim
      - neovim
    state: "{{ should_teardown | ternary('absent', 'latest') }}"
  become: "{{ should_sudo_install }}"

- name: Create directories
  file:
    path: "~/.vim/{{ item }}"
    state: "{{ should_teardown | ternary('absent', 'directory') }}"
    mode: '0755'
  loop:
    - autoload
    - plugged

- name: Copy config
  file:
    src: "{{ should_teardown | ternary(omit, role_path~'/files'~item.src) }}"
    dest: "{{ item.dest }}"
    state: "{{ should_teardown | ternary('absent', 'link') }}"
    force: true
  with_items:
    - src: vimrc
      dest: ~/.vimrc
    - src: nvim
      dest: ~/.config/nvim
    - src: plug.vim
      dest: ~/.vim/autoload/plug.vim
  tags:
    - config
